spring:
  application:
    name: local-travel
  profiles:
    active:
    include: secret
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket:
          name: local-travel-s3

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 7776000 # 90일

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    root: INFO

openai:
  embedding:
    api:
      url: https://api.openai.com/v1/embeddings
    model: text-embedding-3-large

google:
  geocode:
    api:
      url: https://maps.googleapis.com/maps/api/geocode/json
    region: KR
    language: ko
    result-type: country

autocomplete:
  similarity-threshold: 0.28
  limit: 7
